-- MySQL Script generated by MySQL Workbench
-- Fri Jun 17 19:13:42 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_tr_server
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_tr_server` ;

-- -----------------------------------------------------
-- Schema db_tr_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tr_server` DEFAULT CHARACTER SET utf8 ;
USE `db_tr_server` ;

-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_tag` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_tag` (
  `tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `type` TINYINT(4) NULL COMMENT 'null or 0: official tags; 1: user defined tags. default value: 0',
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` TINYINT(4) NULL COMMENT 'default value: 0',
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NULL,
  `passwd` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `third_party_id` VARCHAR(128) NULL,
  `token` VARCHAR(128) NULL,
  `avatar_url` VARCHAR(256) NULL,
  `background_url` VARCHAR(256) NULL,
  `created_time` DATETIME NULL,
  `updated_time` DATETIME NULL,
  `setting_1` TINYINT(4) NULL COMMENT 'default value：1',
  `setting_2` TINYINT(4) NULL COMMENT 'default value: 0',
  `setting_3` TINYINT(4) NULL COMMENT 'default value: 0',
  `setting_4` TINYINT(4) NULL COMMENT 'default value: 0',
  `setting_5` TINYINT(4) NULL COMMENT 'default value: 0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idtbl_user_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_channel` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_channel` (
  `channel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `icon_url` VARCHAR(256) NULL,
  `following_number` INT(11) NULL,
  `created_time` DATETIME NULL,
  `updated_time` DATETIME NULL,
  `visibility_type` TINYINT(4) NULL COMMENT '0: public; 1: followers only; 2: private. default value: 0',
  `creator_id` INT(11) NULL,
  `ownership_type` TINYINT(4) NULL COMMENT '0: single owner; 1: co-editted. default value: 0',
  PRIMARY KEY (`channel_id`),
  UNIQUE INDEX `section_id_UNIQUE` (`channel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_tag_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_tag_channel` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_tag_channel` (
  `tag_channel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tag_id` INT(11) NOT NULL,
  `channel_id` INT(11) NOT NULL,
  PRIMARY KEY (`tag_channel_id`),
  UNIQUE INDEX `tag_section_id_UNIQUE` (`tag_channel_id` ASC),
  INDEX `fk_tbl_tag_section_tbl_tag1_idx` (`tag_id` ASC),
  INDEX `fk_tbl_tag_section_tbl_section1_idx` (`channel_id` ASC),
  CONSTRAINT `fk_tbl_tag_section_tbl_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `db_tr_server`.`tbl_tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_tag_section_tbl_section1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `db_tr_server`.`tbl_channel` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user_channel` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user_channel` (
  `user_channel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `channel_id` INT(11) NOT NULL,
  `following` TINYINT(1) NULL,
  `coediting` TINYINT(1) NULL,
  PRIMARY KEY (`user_channel_id`),
  UNIQUE INDEX `user_section_id_UNIQUE` (`user_channel_id` ASC),
  INDEX `fk_tbl_user_section_tbl_user1_idx` (`user_id` ASC),
  INDEX `fk_tbl_user_section_tbl_section1_idx` (`channel_id` ASC),
  CONSTRAINT `fk_tbl_user_section_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_section_tbl_section1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `db_tr_server`.`tbl_channel` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_article` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_article` (
  `article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_kicker` VARCHAR(128) NULL,
  `article_title` VARCHAR(256) NULL,
  `article_subtitle` VARCHAR(256) NULL,
  `article_desc` VARCHAR(1024) NULL,
  `article_summary` VARCHAR(1024) NULL,
  `article_byline` VARCHAR(128) NULL,
  `article_author` VARCHAR(128) NULL,
  `article_created_date` DATETIME NULL,
  `article_published_date` DATETIME NULL,
  `article_modified_date` DATETIME NULL,
  `article_source` VARCHAR(128) NULL,
  `article_source_url` VARCHAR(256) NULL,
  `source_category` VARCHAR(128) NULL,
  `tags` VARCHAR(256) NULL,
  `images` TEXT NULL,
  `body` MEDIUMTEXT NULL,
  `cluster_tags` VARCHAR(256) NULL,
  `cluster_date` DATETIME NULL,
  `total_words` INT(11) NULL,
  `total_characters` INT(11) NULL,
  `paragraphs` INT(11) NULL,
  `sentences` INT(11) NULL,
  `flesch_ease` FLOAT NULL,
  `flesch_kincaid` FLOAT NULL,
  `analyze_date` DATETIME NULL,
  `smt_data` TEXT NULL,
  `smt_date` DATETIME NULL,
  `format_data` TEXT NULL,
  `created_time` DATETIME NULL,
  `updated_time` DATETIME NULL,
  `status` TINYINT(4) NULL COMMENT 'to be defined. default value: 0',
  PRIMARY KEY (`article_id`),
  UNIQUE INDEX `article_id_UNIQUE` (`article_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_channel_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_channel_article` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_channel_article` (
  `channel_article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `channel_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_time` DATETIME NULL,
  `updated_time` DATETIME NULL,
  `status` TINYINT(4) NULL COMMENT 'to be defined. default value: 0',
  PRIMARY KEY (`channel_article_id`),
  UNIQUE INDEX `section_article_id_UNIQUE` (`channel_article_id` ASC),
  INDEX `fk_tbl_section_article_tbl_article1_idx` (`article_id` ASC),
  INDEX `fk_tbl_section_article_tbl_section1_idx` (`channel_id` ASC),
  INDEX `fk_tbl_section_article_tbl_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_section_article_tbl_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `db_tr_server`.`tbl_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_section_article_tbl_section1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `db_tr_server`.`tbl_channel` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_section_article_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user_article` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user_article` (
  `user_article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `article_id` INT(11) NOT NULL,
  `favorited` TINYINT(1) NULL,
  `bookmarked` TINYINT(1) NULL COMMENT 'do not use at this point',
  `read` TINYINT(1) NULL,
  PRIMARY KEY (`user_article_id`),
  UNIQUE INDEX `user_article_id_UNIQUE` (`user_article_id` ASC),
  INDEX `fk_tbl_user_article_tbl_user1_idx` (`user_id` ASC),
  INDEX `fk_tbl_user_article_tbl_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_tbl_user_article_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_article_tbl_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `db_tr_server`.`tbl_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_search` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_search` (
  `search_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `query_string` VARCHAR(128) NULL,
  `search_time` DATETIME NULL,
  `type` TINYINT(4) NULL COMMENT '0: channel. default value: 0',
  PRIMARY KEY (`search_id`),
  UNIQUE INDEX `search_id_UNIQUE` (`search_id` ASC),
  INDEX `fk_tbl_search_tbl_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_search_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_word` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_word` (
  `word_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` TINYINT(4) NULL COMMENT '0: word; 1: phrase. default value: 0',
  `word` VARCHAR(128) NOT NULL,
  `d_definitions` TEXT NULL,
  `u_definitions` TEXT NULL,
  PRIMARY KEY (`word_id`),
  UNIQUE INDEX `entry_id_UNIQUE` (`word_id` ASC),
  UNIQUE INDEX `word_UNIQUE` (`word` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user_word_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user_word_article` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user_word_article` (
  `user_word_article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `word_id` INT(11) NOT NULL,
  `article_id` INT(11) NOT NULL,
  `start_position` INT(11) NULL,
  `end_position` INT(11) NULL,
  `sentence` TEXT NULL,
  `proposed_definition` VARCHAR(512) NULL COMMENT 'xpath-like path to one definition in the d_definitions field of the tbl_word table',
  `chose_definition` VARCHAR(512) NULL COMMENT 'xpath-like path to one definition in the d_definitions field of the tbl_word table',
  `user_definition` VARCHAR(512) NULL COMMENT 'xpath-like path to one definition in the u_definitions field of the tbl_word table',
  `remembered` TINYINT(1) NULL,
  PRIMARY KEY (`user_word_article_id`),
  UNIQUE INDEX `user_word_article_id_UNIQUE` (`user_word_article_id` ASC),
  INDEX `fk_tbl_user_word_article_tbl_user1_idx` (`user_id` ASC),
  INDEX `fk_tbl_user_word_article_tbl_word1_idx` (`word_id` ASC),
  INDEX `fk_tbl_user_word_article_tbl_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_tbl_user_word_article_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_word_article_tbl_word1`
    FOREIGN KEY (`word_id`)
    REFERENCES `db_tr_server`.`tbl_word` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_word_article_tbl_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `db_tr_server`.`tbl_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_hot_search_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_hot_search_channel` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_hot_search_channel` (
  `hot_search_id` INT(11) NOT NULL AUTO_INCREMENT,
  `query_string` VARCHAR(128) NOT NULL,
  `search_count` INT(11) NULL,
  PRIMARY KEY (`hot_search_id`),
  UNIQUE INDEX `hot_search_id_UNIQUE` (`hot_search_id` ASC),
  UNIQUE INDEX `query_string_UNIQUE` (`query_string` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user_tag` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user_tag` (
  `user_tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tag_id` INT(11) NOT NULL,
  `creator_id` INT(11) NOT NULL,
  `created_time` DATETIME NULL,
  `updated_time` DATETIME NULL,
  PRIMARY KEY (`user_tag_id`),
  UNIQUE INDEX `user_tag_id_UNIQUE` (`user_tag_id` ASC),
  INDEX `fk_tbl_user_tag_tbl_tag1_idx` (`tag_id` ASC),
  INDEX `fk_tbl_user_tag_tbl_user1_idx` (`creator_id` ASC),
  CONSTRAINT `fk_tbl_user_tag_tbl_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `db_tr_server`.`tbl_tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_tag_tbl_user1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tr_server`.`tbl_user_article_share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tr_server`.`tbl_user_article_share` ;

CREATE TABLE IF NOT EXISTS `db_tr_server`.`tbl_user_article_share` (
  `user_article_share_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `article_id` INT(11) NOT NULL,
  `type` TINYINT(4) NULL COMMENT '0: weixin friends; 1: weixin circle; 2: qq; 3: qzone; 4: weibo; 5: sms; 6: email',
  `created_time` DATETIME NULL,
  PRIMARY KEY (`user_article_share_id`),
  UNIQUE INDEX `user_article_share_id_UNIQUE` (`user_article_share_id` ASC),
  INDEX `fk_tbl_user_article_share_tbl_user1_idx` (`user_id` ASC),
  INDEX `fk_tbl_user_article_share_tbl_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_tbl_user_article_share_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tr_server`.`tbl_user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_article_share_tbl_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `db_tr_server`.`tbl_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
